// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5AMer8pGOxk3lAzDLnpv7lMWS1fHD9fM',
    appId: '1:856690175231:web:23bec57450f83ac3e5f0ca',
    messagingSenderId: '856690175231',
    projectId: 'evotingsystem-33ccd',
    authDomain: 'evotingsystem-33ccd.firebaseapp.com',
    databaseURL: 'https://evotingsystem-33ccd-default-rtdb.firebaseio.com',
    storageBucket: 'evotingsystem-33ccd.firebasestorage.app',
    measurementId: 'G-VTTZRWSRFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWoIdpZo12RjKtktoVxErRkNqWO7C43tU',
    appId: '1:856690175231:android:05e878f5a8152ca7e5f0ca',
    messagingSenderId: '856690175231',
    projectId: 'evotingsystem-33ccd',
    databaseURL: 'https://evotingsystem-33ccd-default-rtdb.firebaseio.com',
    storageBucket: 'evotingsystem-33ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4igr-myPd0rzyuMBHvdCGQbo_g44Vyw',
    appId: '1:856690175231:ios:ca7c200abb5a7690e5f0ca',
    messagingSenderId: '856690175231',
    projectId: 'evotingsystem-33ccd',
    databaseURL: 'https://evotingsystem-33ccd-default-rtdb.firebaseio.com',
    storageBucket: 'evotingsystem-33ccd.firebasestorage.app',
    iosBundleId: 'com.example.eVotingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4igr-myPd0rzyuMBHvdCGQbo_g44Vyw',
    appId: '1:856690175231:ios:ca7c200abb5a7690e5f0ca',
    messagingSenderId: '856690175231',
    projectId: 'evotingsystem-33ccd',
    databaseURL: 'https://evotingsystem-33ccd-default-rtdb.firebaseio.com',
    storageBucket: 'evotingsystem-33ccd.firebasestorage.app',
    iosBundleId: 'com.example.eVotingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5AMer8pGOxk3lAzDLnpv7lMWS1fHD9fM',
    appId: '1:856690175231:web:00accd9acf00e26be5f0ca',
    messagingSenderId: '856690175231',
    projectId: 'evotingsystem-33ccd',
    authDomain: 'evotingsystem-33ccd.firebaseapp.com',
    databaseURL: 'https://evotingsystem-33ccd-default-rtdb.firebaseio.com',
    storageBucket: 'evotingsystem-33ccd.firebasestorage.app',
    measurementId: 'G-JBY5YV84EQ',
  );

}